apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-db-pvc
  namespace: todo-app
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-db
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-db
  template:
    metadata:
      labels:
        app: tasks-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: tasks-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-db
  namespace: todo-app
spec:
  selector:
    app: tasks-db
  ports:
  - port: 5432