apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: frontend
        image: menouerthinhinane/frontend:latest
        ports: [{ containerPort: 5000 }]
        env:  # ‚Üê AJOUTE CETTE SECTION
        - name: USERS_URL
          value: "http://users:5001"
        - name: TASKS_URL
          value: "http://tasks:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo-app
spec:
  selector: { app: frontend }
  ports: [{ port: 5000 }]
