---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
      annotations:
        sidecar.istio.io/inject: "true"   # Active le proxy Istio pour mTLS
    spec:
      containers:
      - name: tasks
        image: marglou/tasks:latest     # DOCKER__USERNAME
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          value: "tasks-db-service" 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasks-db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: tasks
  namespace: todo-app
spec:
  selector:
    app: tasks
  ports:
  - port: 5002